### ISSUE TITLE
Crash in zrepl daemon

### ISSUE THREAD

**Issue by zdykstra** [dsh2dsh/zrepl#2]
Using zrepl 0.7.6 on Void linux, I'm getting a crash in the daemon while executing a job.  The configuration was working with one of the first releases tagged in this repo, 0.6.6.  Attached is a debug log and the zrepl.yaml that was used. I'm happy to provide additional details as needed.

[zrepl.debug.txt](https://github.com/user-attachments/files/15523373/zrepl.debug.txt)
[zrepl.yml.txt](https://github.com/user-attachments/files/15523382/zrepl.yml.txt)

**Comment by dsh2dsh** [comment]
Hi,

Sorry, I didn't get a notification about this issue. Could you try to reproduce this crash using latest 0.8.0 version?

**Comment by dsh2dsh** [comment]
Feedback timeout.

**Comment by zdykstra** [comment]
I built 0.8.2 locally on Void and I can confirm that it's working as expected now. Lots of nice improvements in there, thanks for continuing to drive this project forward!

**Comment by dsh2dsh** [comment]
Glad to see it, thank you.
