### ISSUE TITLE
Feature: configurable missed job timeout

### ISSUE THREAD

**Issue by robertek** [dsh2dsh/zrepl#7]
This is hopefully the last issue I'm noticing now :). Or let say it is more like a nice to have.

I have noticed that on system that is frequently suspended (laptop), the missed cron job is woken up after some timeout. I don't know how long this timeout is (?30min?) and I would like to make it shorter (5min).

An example I have observed is a regular hourly cron job. When I resume the system and the job has negative time to execute it took some time to reset. I suspect this is 30 min, but did not found that in the code.

My observation:
- cron job (5 * * * *)
- resumed around 15:53
- time to execute shown as negative (slept more than a hour)
- 16:05 when the job is expected to execute nothing happened
- 16:23 (from the logs) the job is executed and scheduled to a correct new time

It would be nice to have something like this:
```
general:
  # how long to wait until missed job is re-executed
  missed-job-timeout: 30m
```

A general workaround is to restart the daemon after the system is resumed, but it has a downside of skipping some of the missed jobs (like remote replicating job, which may be scheduled for example once a day).

**Comment by dsh2dsh** [comment]
Well, that's a problem. Internally all jobs are scheduled to wakeup in X seconds of uptime. It isn't scheduled to wakeup at specific time like at 15:53. So when your laptop is sleeping, the job's clock isn't ticking. So if, before sleep, next job will be in 30 minutes, it means, after resume it still be in 30 minutes. Upstream handles this situation, but I decided the best solution is to stop zrepl before sleep and start it back on resume. May be later I'll implement something like `zrepl signal resume`, which'll find all missed jobs and weakup them. Or may be I'll add a goroutine, which will do this check periodically, every configured time. Yeah, definitely I'll implement something like that later, so lets keep this issue opened.

**Comment by dsh2dsh** [comment]
Please test master branch.

**Comment by dsh2dsh** [comment]
Included into the latest release.

**Comment by robertek** [comment]
I have tested it and it is working. Thanks.
